name: CI/CD for Test Flask App

on:
  push:
    branches:
      - main
      - feature/tests 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: python -m unittest discover -s . -p '*.py'
  
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout/v2

      - name: Set up Python
        uses: actions/setup-python/v2
        with:
          python-version: 3.12
          
      - name: Create virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependancies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Deploy production
        uses: johnybeynon/render-deploy-action@v0.0.8
        with:
         service-id: ${{ secrets.SERVICE_ID}}
         api-key: ${{ secrets.RENDER_API_KEY}}

